/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_luismendoza;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author luiscarlomendoza
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_oyente = new javax.swing.JDialog();
        jd_artista = new javax.swing.JDialog();
        jd_signUpUser = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt_oyenteUser = new javax.swing.JTextField();
        jt_oyentePass = new javax.swing.JTextField();
        jt_oyenteEdad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jb_guardarOyente = new javax.swing.JButton();
        jd_signUpArtist = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jt_nameSignUpArtist = new javax.swing.JTextField();
        jt_usernameSignUpArtist = new javax.swing.JTextField();
        jt_passwordSignUpArtist = new javax.swing.JTextField();
        jt_edadSignUpArtist = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jb_LogIn = new javax.swing.JButton();
        jb_SignUpUser = new javax.swing.JButton();
        jb_SignUpArtist = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_user = new javax.swing.JTextField();
        jp_password = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jd_oyenteLayout = new javax.swing.GroupLayout(jd_oyente.getContentPane());
        jd_oyente.getContentPane().setLayout(jd_oyenteLayout);
        jd_oyenteLayout.setHorizontalGroup(
            jd_oyenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jd_oyenteLayout.setVerticalGroup(
            jd_oyenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_artistaLayout = new javax.swing.GroupLayout(jd_artista.getContentPane());
        jd_artista.getContentPane().setLayout(jd_artistaLayout);
        jd_artistaLayout.setHorizontalGroup(
            jd_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_artistaLayout.setVerticalGroup(
            jd_artistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel4.setText("Username");

        jLabel5.setText("Password");

        jLabel6.setText("Edad");

        jLabel7.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel7.setText("Sign Up User");

        jb_guardarOyente.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jb_guardarOyente.setText("Guardar");
        jb_guardarOyente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_guardarOyente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarOyenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_signUpUserLayout = new javax.swing.GroupLayout(jd_signUpUser.getContentPane());
        jd_signUpUser.getContentPane().setLayout(jd_signUpUserLayout);
        jd_signUpUserLayout.setHorizontalGroup(
            jd_signUpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signUpUserLayout.createSequentialGroup()
                .addGroup(jd_signUpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_signUpUserLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jd_signUpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(jd_signUpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_oyentePass, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jt_oyenteUser)
                            .addComponent(jt_oyenteEdad)))
                    .addGroup(jd_signUpUserLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_signUpUserLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jb_guardarOyente)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jd_signUpUserLayout.setVerticalGroup(
            jd_signUpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signUpUserLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jd_signUpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_oyenteUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_signUpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_oyentePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_signUpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jt_oyenteEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_guardarOyente)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel8.setText("Sign Up Artist");

        jLabel9.setText("Username");

        jLabel10.setText("Edad");

        jLabel11.setText("Password");

        jLabel12.setText("Name");

        jButton1.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_signUpArtistLayout = new javax.swing.GroupLayout(jd_signUpArtist.getContentPane());
        jd_signUpArtist.getContentPane().setLayout(jd_signUpArtistLayout);
        jd_signUpArtistLayout.setHorizontalGroup(
            jd_signUpArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signUpArtistLayout.createSequentialGroup()
                .addGroup(jd_signUpArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_signUpArtistLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_signUpArtistLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jd_signUpArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_signUpArtistLayout.createSequentialGroup()
                                .addGroup(jd_signUpArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jd_signUpArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jt_passwordSignUpArtist)
                                    .addComponent(jt_edadSignUpArtist, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                            .addGroup(jd_signUpArtistLayout.createSequentialGroup()
                                .addGroup(jd_signUpArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jd_signUpArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jt_nameSignUpArtist, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(jt_usernameSignUpArtist)))))
                    .addGroup(jd_signUpArtistLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton1)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jd_signUpArtistLayout.setVerticalGroup(
            jd_signUpArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signUpArtistLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(15, 15, 15)
                .addGroup(jd_signUpArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jt_nameSignUpArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signUpArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jt_usernameSignUpArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signUpArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jt_passwordSignUpArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signUpArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jt_edadSignUpArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 0));

        jb_LogIn.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jb_LogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab6p2_luismendoza/enter2.png"))); // NOI18N
        jb_LogIn.setText("Ingresar");
        jb_LogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_LogInMouseClicked(evt);
            }
        });

        jb_SignUpUser.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jb_SignUpUser.setText("SignUp User");
        jb_SignUpUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_SignUpUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SignUpUserMouseClicked(evt);
            }
        });

        jb_SignUpArtist.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jb_SignUpArtist.setText("SignUp Artist");
        jb_SignUpArtist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_SignUpArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SignUpArtistMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Zapfino", 0, 13)); // NOI18N
        jLabel1.setText("Welcome to FAKE Spotify");

        jLabel2.setText("Username ");

        jLabel3.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jb_LogIn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(157, 157, 157)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jt_user, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(jp_password)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(224, 224, 224)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jb_SignUpArtist)
                                .addComponent(jb_SignUpUser)))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jp_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jb_LogIn)
                .addGap(18, 18, 18)
                .addComponent(jb_SignUpUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_SignUpArtist)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_LogInMouseClicked
        // TODO add your handling code here:

        if (users.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Aun no hay usuarios");
        } else {
            for (int i = 0; i < users.size(); i++) {
                if (jt_user.getText().equals(users.get(i).getUsername())) {
                    if (jp_password.getText().equals(users.get(i).getPassword())) {
                        currentUser = users.get(i);
                    }
                }

            }

            if (currentUser instanceof Artista) {
                
                JOptionPane.showMessageDialog(this, "Bienvenido " + currentUser.getUsername());
                
                jd_artista.setModal(true);
                jd_artista.pack();
                jd_artista.setLocationRelativeTo(this);
                jd_artista.setVisible(true);

            } else if (currentUser instanceof Oyente) {
                
                JOptionPane.showMessageDialog(this, "Bienvenido " + currentUser.getUsername());
                
                jd_oyente.setModal(true);
                jd_oyente.pack();
                jd_oyente.setLocationRelativeTo(this);
                jd_oyente.setVisible(true);

            }
        }
    }//GEN-LAST:event_jb_LogInMouseClicked

    private void jb_SignUpUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SignUpUserMouseClicked
        // TODO add your handling code here:
        
        jd_signUpUser.setModal(true);
        jd_signUpUser.pack();
        jd_signUpUser.setLocationRelativeTo(this);
        jd_signUpUser.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jb_SignUpUserMouseClicked

    private void jb_SignUpArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SignUpArtistMouseClicked
        // TODO add your handling code here:
        jd_signUpArtist.setModal(true);
        jd_signUpArtist.pack();
        jd_signUpArtist.setLocationRelativeTo(this);
        jd_signUpArtist.setVisible(true);
        
    }//GEN-LAST:event_jb_SignUpArtistMouseClicked

    private void jb_guardarOyenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarOyenteMouseClicked
        // TODO add your handling code here:
        String user = jt_oyenteUser.getText();
        String password= jt_oyentePass.getText();
        int edad = Integer.parseInt(jt_oyenteEdad.getText());
        
        Oyente oyente = new Oyente(user,password,edad);
        users.add(oyente);
        
        JOptionPane.showMessageDialog(jd_signUpUser, "Se ha creado con éxito");
        System.out.println(users);
    }//GEN-LAST:event_jb_guardarOyenteMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String name = jt_nameSignUpArtist.getText();
        String user = jt_usernameSignUpArtist.getText();
        String password= jt_passwordSignUpArtist.getText();
        int edad = Integer.parseInt(jt_edadSignUpArtist.getText());
        
        Artista artista = new Artista(name,user,password,edad);
        users.add(artista);
        System.out.println(users);
        
        JOptionPane.showMessageDialog(jd_signUpArtist, "Se guardo con éxito");
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jb_LogIn;
    private javax.swing.JButton jb_SignUpArtist;
    private javax.swing.JButton jb_SignUpUser;
    private javax.swing.JButton jb_guardarOyente;
    private javax.swing.JDialog jd_artista;
    private javax.swing.JDialog jd_oyente;
    private javax.swing.JDialog jd_signUpArtist;
    private javax.swing.JDialog jd_signUpUser;
    private javax.swing.JPasswordField jp_password;
    private javax.swing.JTextField jt_edadSignUpArtist;
    private javax.swing.JTextField jt_nameSignUpArtist;
    private javax.swing.JTextField jt_oyenteEdad;
    private javax.swing.JTextField jt_oyentePass;
    private javax.swing.JTextField jt_oyenteUser;
    private javax.swing.JTextField jt_passwordSignUpArtist;
    private javax.swing.JTextField jt_user;
    private javax.swing.JTextField jt_usernameSignUpArtist;
    // End of variables declaration//GEN-END:variables

    Usuario currentUser;
    ArrayList<Usuario> users = new ArrayList();

}
